openapi: 3.0.1
info:
  title: TellyHealth API
  version: 1.0.0
  license:
    name: MIT
paths:
  /healthcheck:
    get:
      summary: Health check
      description: End point to check health check
      operationId: getHealthCheck
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "\U0001F44D"
  /user/register/medical_practitoner:
    post:
      summary: Medical practitoner registration
      description: Register user as medical practitoner
      operationId: createMedicalPractitonerUser
      responses:
        '200':
          description: User created successfully
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MedicalPractitoner'
            application/json:
              schema:
                $ref: '#/components/schemas/MedicalPractitoner'
        '405':
          description: Invalid input
      requestBody:
        description: Create a new medical practitoner user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicalPractitoner'
          application/xml:
            schema:
              $ref: '#/components/schemas/MedicalPractitoner'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MedicalPractitoner'
  /user/register/individual:
    post:
      summary: Patient registration
      description: Register user as patient
      operationId: createIndividualUser
      responses:
        '200':
          description: User created successfully
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Individual'
            application/json:
              schema:
                $ref: '#/components/schemas/Individual'
        '405':
          description: Invalid input
      requestBody:
        description: Create a new patient user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Individual'
          application/xml:
            schema:
              $ref: '#/components/schemas/Individual'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Individual'
  /contact/save:
    post:
      summary: Contact enquiry messages
      description: Contact enquiry messages from site users
      operationId: createContact
      responses:
        '200':
          description: Contact was saved successfully
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '405':
          description: Invalid input
      requestBody:
        description: Create a new enquiry
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/xml:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
components:
  schemas:
    MedicalPractitoner:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Dr.John
        email:
          type: string
          example: john@email.com
        country:
          type: string
          example: Australia
        location:
          type: string
          example: "12.00,43.02"
        timezone:
          type: string
          example: "Sydney/Australia"
        specialization:
          type: string
          example: "Dermatology"
        languages:
          type: array
          example: ["Tamil", "English"]
          items:
            type: string
        preferredConsultation:
          type: array
          example: ["webinar", "one-to-one"]
          items:
            type: string
        phoneNumber:
          type: string
          example: "+61406210236"
        emailVerified:
          type: boolean
          example: false
          description: Email Status
      xml:
        name: medical_practitoner
      type: object
    Individual:
      properties:
        id:
          type: integer
          format: int64
          example: 11
        name:
          type: string
          example: Richard Branson
        email:
          type: string
          example: richard@email.com
        country:
          type: string
          example: Australia
        location:
          type: string
          example: "12.00,43.02"
        timezone:
          type: string
          example: "Sydney/Australia"
        preferredSpecialist:
          type: string
          example: "Dermatology"
        languages:
          type: array
          example: ["Tamil", "English"]
          items:
            type: string
        preferredConsultation:
          type: array
          example: ["group", "one-to-one"]
          items:
            type: string
        preferredConsultationDate:
          type: string
          example: "2022-05-16T10:19:00.000Z"
        phoneNumber:
          type: string
          example: "+61406210236"
        emailVerified:
          type: boolean
          example: false
          description: Email Status
        additionalMessage:
          type: string
          example: "Additional consultation message"
      xml:
        name: individual
      type: object
    Contact:
      properties:
        id:
          type: integer
          format: int64
          example: 11
        name:
          type: string
          example: Richard Branson
        email:
          type: string
          example: richard@email.com
        country:
          type: string
          example: Australia
        location:
          type: string
          example: "12.00,43.02"
        phoneNumber:
          type: string
          example: "+61406210236"
        message:
          type: string
          example: "Contact message"
      xml:
        name: contact
      type: object       
tags: []