service: tellyhealth-api
useDotenv: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-jest-plugin

custom:
  jest:
    testEnvironment: node
    testRunner: jest-circus/runner
    testMatch: 
      - '<rootDir>/test/integration /**/*.test.ts'
    globals:
      'ts-jest':
        'tsconfig': './tsconfig.test.json'
    transform:
      '^.+\\.ts$': 'ts-jest'
    moduleFileExtensions:
      - ts
      - js
      - json


provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

functions:
  app:
   # handler: src/handler.ts
    handler: dist/cjs/handler.handler
    events:
      - http: 'GET /healthcheck'
      - http: 'POST /auth/register/{role}'
      - http: 'POST /auth/update_profile'
      - http: 'POST /auth/verify-email'
      - http: 'POST /auth/login/email'
      - http: 'POST /auth/login'