service: my-express-application
useDotenv: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-jest-plugin

custom:
  jest:
    testEnvironment: node
    testRunner: jest-circus/runner
    testMatch: 
      - '<rootDir>/test/unit /**/*.test.ts'
    globals:
      'ts-jest':
        'tsconfig': './tsconfig.test.json'
    transform:
      '^.+\\.ts$': 'ts-jest'
    moduleFileExtensions:
      - ts
      - js
      - json


provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

functions:
  app:
    handler: src/handler.ts
    events:
      - http: 'GET /healthcheck'
      - http: 'POST /auth/register/:role'