name: 'WEBSITE UI CI'

on:
  push:
    branches: ['*/*']
  # release:
  #   types: [published]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui/website
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
          NETLIFY_SITE_ID: ${{ secrets.WEBSITE_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_SECRET }}
