name: 'WEBSITE UI CI'

on:
  push:
    branches: ['*/*']
  # release:
  #   types: [published]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui/website
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Build the package
        run: npm run build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=/home/runner/work/tellyhealth/tellyhealth/packages/ui/website/public --prod --auth ${{ secrets.NETLIFY_SECRET }} --site ${{ secrets.WEBSITE_SITE_ID }}
